imports:
    - { resource: config.yml }

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
    orm:
        auto_mapping: true
