sonata_block:
    blocks:
        blast_dashboard.main_block: ~

sonata_admin:
    dashboard:
        blocks:
            -
                class:    col-xs-12
                position: top
                type:     blast_dashboard.main_block
