services:
#    blast_core.twig.base_extension:
#        class: Blast\CoreBundle\Twig\Extensions\BaseExtension
#        tags: [{ name: twig.extension }]
#        calls:
#            - [setRouter,[@router]]

    sonata.admin.exporter:
        class: Blast\CoreBundle\Admin\Exporter
        calls:
            - [setRouter, ['@router']]

    blast_core.label.strategy.librinfo:
        class: Blast\CoreBundle\Translator\LibrinfoLabelTranslatorStrategy

    ######### FORM TYPES ###########
    blast_core.form.type.entity_code:
        class: Blast\CoreBundle\Form\Type\EntityCodeType
        tags:
            - { name: form.type, alias: librinfo_entitycode }


    #########  ENTITY CODE GENERATORS ############
    blast_core.code_generator_factory:
        class: Blast\CoreBundle\CodeGenerator\CodeGeneratorFactory
    blast_core.code_generators:
        class: Blast\CoreBundle\CodeGenerator\CodeGeneratorRegistry