services:

    sonata.admin.admin_exporter:
        class: Blast\Bundle\CoreBundle\Admin\AdminExporter
        arguments: ['@sonata.exporter.exporter']
        calls:
            - [setTokenStorage, ['@security.token_storage']]
            - [setTranslator, ['@translator']]
            - [setTwig, ['@twig']]
            - [setRouter, ['@router']]

    sonata.exporter.exporter:
        class: Blast\Bundle\CoreBundle\Exporter\Exporter

    ######### FORM TYPES ###########
    blast_core.form.type.entity_code:
        class: Blast\Bundle\CoreBundle\Form\Type\EntityCodeType
        tags:
            - { name: form.type, alias: blast_entitycode }


    #########  ENTITY CODE GENERATORS ############
    blast_core.code_generator_factory:
        class: Blast\Bundle\CoreBundle\CodeGenerator\CodeGeneratorFactory
    blast_core.code_generators:
        class: Blast\Bundle\CoreBundle\CodeGenerator\CodeGeneratorRegistry

    ############ TWIG EXTENSIONS ##########
    blast_core.extension.global_search:
        class: Blast\Bundle\CoreBundle\Twig\GlobalSearchExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    blast_core.extension.global_search:
        class: Blast\Bundle\CoreBundle\Twig\GlobalSearchExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    ############ HOOK ##########
    blast_core.twig.fake_hook:
        class: Blast\Bundle\CoreBundle\Twig\FakeHook
        arguments:
            - '@service_container'
            - '%kernel.environment%'
        tags:
            - { name: twig.extension }

    blast_core.doctrine.orm.cascading_relation_checker:
        class: Blast\Bundle\CoreBundle\Doctrine\ORM\CascadingRelationChecker
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
