# Package `sllh/php-cs-fixer-styleci-bridge` is required to get it working.

preset: psr2

#disabled:
#  - concat_without_spaces
#  - single_quote

enabled:
  - no_php4_constructor
  - concat_with_spaces
