services:

    sonata.admin.exporter:
        class: Blast\CoreBundle\Admin\Exporter
        calls:
            - [setRouter, ['@router']]

    blast_core.label.strategy.librinfo:
        class: Blast\CoreBundle\Translator\LibrinfoLabelTranslatorStrategy

    ######### FORM TYPES ###########
    blast_core.form.type.entity_code:
        class: Blast\CoreBundle\Form\Type\EntityCodeType
        tags:
            - { name: form.type, alias: librinfo_entitycode }


    #########  ENTITY CODE GENERATORS ############
    blast_core.code_generator_factory:
        class: Blast\CoreBundle\CodeGenerator\CodeGeneratorFactory
    blast_core.code_generators:
        class: Blast\CoreBundle\CodeGenerator\CodeGeneratorRegistry

    ############ TWIG EXTENSIONS ##########
    blast_core.extension.global_search:
        class: Blast\CoreBundle\Twig\GlobalSearchExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    blast_core.profiler.collector:
        class: Blast\CoreBundle\Profiler\Collector

    blast_core.profiler.admin_collector:
        class: Blast\CoreBundle\Profiler\AdminCollector
        calls:
            - [setCollector,['@blast_core.profiler.collector']]
        tags:
             -
                name:     data_collector
                template: 'BlastCoreBundle:Profiler/AdminCollector:toolbar.html.twig'
                id:       'blast.admin_collector'
        public: false
